// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "controllers"
import "@hotwired/turbo-rails"
import * as bootstrap from "bootstrap"
import "./utilities/test_timer"
import "./utilities/disable_paste"
import "./utilities/close_flash_messages"
import "./utilities/turbo_confirm"
import "./utilities/dom_reloader"
import "./utilities/checkbox"
import "./utilities/sort_by_group"
import "./utilities/search_input"
import "./utilities/essay_input_counter"
